### ISSUE TITLE
Implement addPermission() in DrivePermissionManager class

### ISSUE THREAD

**Issue by bsu-jacksonmorton** [cs481-ekh/f22-softskills#152]
Now that we have managed to have basic file/permission enumeration from the Google Drive API, we need to start implementing the logic to update or add to the permissions in the user's Google Drive account. The server route that handles add permission requests needs this method to carry out those requests.

Acceptance Criteria:

- [x] When a call to addPermission() is made, if the fileId is invalid (not in our DB), then an exception is thrown.
- [x] When a call to addPermission() is made, if the role type is invalid, then an exception is thrown.
- [x] When a call to addPermission() is made, if the grantee type is invalid, then an exception is thrown.
- [x] When a call to addPermission() is made, if the s parameter provided is not a valid email or domain, then an exception is thrown.
- [x] When a call to addPermission() is made, if the user does not have access to or is not the owner of the fileId, then an exception is thrown.
- [x] When a call to addPermission() is made, if all parameters are valid, the user owns the fileId, and the API call to Google Drive was successful, then the permission should be updated in our DB.
- [x] When a call to addPermission() is made, if all parameters are valid, the user owns the fileId, and the API call to Google Drive was unsuccessful, then the permission should not be updated in our DB and an exception should be thrown.

Tasks:

- [x] Implement parameter checking logic for addPermission() #153 
- [x] Implement API call to Google Drive to create permission #154 
- [x] Implement logic to add a successfully created permission to our database #155
