### ISSUE TITLE
Implement deletePermission() in DrivePermissionManager

### ISSUE THREAD

**Issue by bsu-jacksonmorton** [cs481-ekh/f22-softskills#156]
Now that we have managed to have basic file/permission enumeration from the Google Drive API, we need to start implementing the logic to update or add to the permissions in the user's Google Drive account. The server route that handles delete permission requests needs this method to carry out those requests.

Acceptance Criteria:

- [x] When a call is made to deletePermission(), if an invalid fileId is passed, an exception is thrown
- [x] When a call is made to deletePermission(), if an invalid permissionId is passed, an exception is thrown.
- [x] When a call is made to deletePermission(), if the fileId and permissionId are valid but the user making the request is not the owner, an exception is thrown.
- [x] When a call is made to deletePermission(), if the fileId and permissionId are valid and the user is the owner, the permission is removed.

Tasks: 

- [x] Implement the logic to parse the parameters in deletePermission() #157 
- [x] Implement the logic to make the API call to Google Drive to delete the permission in deletePermission() #158 
- [x] Implement the logic to update the DB upon successful deletion of the permission in deletePermission() #159
