### ISSUE TITLE
Create test suite for the addPermission() method of the DrivePermissionManager class

### ISSUE THREAD

**Issue by bsu-jacksonmorton** [cs481-ekh/f22-softskills#160]
As a developer, I need a test suite for addPermission(), so that I know the software is working as it should be.

Acceptance Criteria:

- [x] There is a test for an invalid form of each parameter of addPermission()
- [x] There is a test for valid forms of each parameter of addPermission()

Tasks:

- [x] Create a test for invalid fileId #162 
- [x] Create a test for valid fileId #163 
- [x] Create a test for invalid Grantee Type #164 
- [x] Create a test for valid Grantee Type #165 
- [x] Create a test for invalid Role #166 
- [x] Create a test for valid Role #167 
- [x] Create a test for invalid email / domain #168 
- [x] Create a test for valid email / domain #169
