### ISSUE TITLE
Create Drive Permissions Manager Interface

### ISSUE THREAD

**Issue by bsu-jacksonmorton** [cs481-ekh/f22-softskills#48]
As a developer, I want an interface for the Drive Permission Manager so that I can work on another piece of the code base simultaneously that is dependent on knowing the I/O of the API.

## Definition of Done
- [x] Code builds without error
- [x] Code is properly documented
- [x] Code is merged into the main branch of the repo

## Tasks
- [x] #49 
- [x] #50 
- [x] #51 
- [x] #52 
- [x] #53
